"use client";

import Link from "next/link";
import { ArrowRight, BarChart2, Briefcase, Code, ShieldCheck } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col justify-center items-center p-8 relative overflow-hidden dark">
      {/* Background Orbs */}
      <div className="absolute top-20 left-10 w-72 h-72 bg-purple-500/20 rounded-full blur-3xl -z-10 animate-pulse" />
      <div className="absolute bottom-20 right-10 w-96 h-96 bg-blue-500/20 rounded-full blur-3xl -z-10 animate-pulse delay-1000" />
      
      <main className="max-w-5xl mx-auto flex flex-col items-center text-center space-y-12 z-10">
        
        {/* Hero Section */}
        <div className="space-y-6 animate-in slide-in-from-bottom-8 duration-700">
          <div className="inline-flex items-center rounded-full border border-blue-500/30 bg-blue-500/10 px-3 py-1 text-sm font-medium text-blue-300 backdrop-blur-md mb-4">
            <span className="flex h-2 w-2 rounded-full bg-blue-500 mr-2 animate-ping" />
            apniLeap AURA — Agentic Evaluation Active
          </div>
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight">
            Placement Readiness & <br />
            <span className="text-gradient">Career Intelligence</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            A single view of your placement readiness, skill gaps, company fit, and structured upskilling — backed by faculty-reviewed AI assessment.
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 animate-in slide-in-from-bottom-10 duration-1000 delay-150">
          <Link 
            href="/onboarding" 
            className="group relative inline-flex items-center justify-center overflow-hidden rounded-full p-4 px-8 font-medium text-white bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 shadow-[0_0_40px_-10px_rgba(79,70,229,0.5)] transition-all"
          >
            <span className="absolute right-0 translate-x-full transition-transform group-hover:-translate-x-4">
              <ArrowRight className="h-5 w-5" />
            </span>
            <span className="transition-transform group-hover:-translate-x-4 font-semibold">Start Evaluation</span>
          </Link>
          
          <Link 
            href="/officer" 
            className="inline-flex items-center justify-center rounded-full px-8 py-4 font-medium text-foreground glass hover:bg-white/5 transition-all"
          >
            <ShieldCheck className="mr-2 h-5 w-5 text-purple-400" />
            Placement Cell Access
          </Link>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-16 w-full animate-in fade-in duration-1000 delay-300">
          
          <div className="glass-card flex flex-col items-center text-center space-y-4">
            <div className="p-3 bg-blue-500/20 rounded-xl">
              <Briefcase className="h-8 w-8 text-blue-400" />
            </div>
            <h3 className="text-lg font-semibold">Target Role Matching</h3>
            <p className="text-sm text-muted-foreground">Benchmark your skills against real company requirements with data-driven confidence scores.</p>
          </div>

          <div className="glass-card flex flex-col items-center text-center space-y-4">
            <div className="p-3 bg-purple-500/20 rounded-xl">
              <Code className="h-8 w-8 text-purple-400" />
            </div>
            <h3 className="text-lg font-semibold">Coding Analytics</h3>
            <p className="text-sm text-muted-foreground">Aggregate LeetCode and GitHub activity into actionable difficulty distribution and activity trends.</p>
          </div>

          <div className="glass-card flex flex-col items-center text-center space-y-4">
            <div className="p-3 bg-pink-500/20 rounded-xl">
              <BarChart2 className="h-8 w-8 text-pink-400" />
            </div>
            <h3 className="text-lg font-semibold">Learning Roadmap</h3>
            <p className="text-sm text-muted-foreground">Get a personalized, timeline-based upskilling plan generated by the Interview Agent.</p>
          </div>

        </div>
      </main>
    </div>
  );
}
