"""
Interview Agent (A5) — Generates role-specific mock interview Q&A + learning roadmap.

Architecture Contract:
- Input: student_profile, skill_gap_report, target_role, session_type
- Output: questions (with type, difficulty, targeted skill), evaluation, roadmap_items
- Tools: question_bank (mock for Lab 7), skill_gap_reader
- Constraints: Mark ALL feedback as AI-generated, adapt to skill gaps, keep sessions private
- LLM Usage: Question generation, answer evaluation (both clearly AI-labelled)
- Deterministic Logic: Score calculation, roadmap structure, priority ordering

The Interview Agent generates questions adapted to identified skill gaps,
provides AI-evaluated feedback, and creates an actionable learning roadmap.
ALL LLM output is explicitly labelled as AI-generated.
"""
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone
import logging

from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from app.config import settings
from app.agents.state import PlacementState, AuditEvent

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pydantic schemas for structured LLM output
# ---------------------------------------------------------------------------

class InterviewQuestionSchema(BaseModel):
    """A single interview question generated by the LLM."""
    text: str = Field(description="The interview question text")
    question_type: str = Field(description="One of: 'technical', 'behavioral', 'system_design', 'coding'")
    difficulty: str = Field(description="One of: 'easy', 'medium', 'hard'")
    skill_targeted: str = Field(description="The specific skill this question tests")
    expected_answer_outline: str = Field(description="Brief outline of what a good answer would cover")
    scoring_rubric: str = Field(description="How to evaluate the answer: key points to look for")


class RoadmapItemSchema(BaseModel):
    """A single learning roadmap item."""
    skill: str = Field(description="The skill to develop")
    title: str = Field(description="Title of the learning activity")
    description: str = Field(description="What to do and why")
    priority: str = Field(description="One of: 'critical', 'high', 'medium', 'low'")
    resources: List[str] = Field(description="Specific learning resources (courses, docs, practice sites)")
    estimated_hours: int = Field(description="Estimated hours to complete")
    milestone: str = Field(description="What success looks like after completing this item")


class InterviewOutput(BaseModel):
    """Full structured output from the Interview Agent."""
    questions: List[InterviewQuestionSchema] = Field(description="5-8 interview questions adapted to the student's gaps")
    mock_evaluation: Dict[str, Any] = Field(
        description="Mock evaluation summary assuming average performance. "
                    "This is a TEMPLATE — real evaluation happens when student takes the interview."
    )
    roadmap_items: List[RoadmapItemSchema] = Field(description="5-10 learning roadmap items prioritized by gap severity")
    preparation_tips: List[str] = Field(description="3-5 specific preparation tips for this student")


# ---------------------------------------------------------------------------
# Deterministic helper functions
# ---------------------------------------------------------------------------

PRIORITY_WEIGHTS = {"critical": 4, "high": 3, "medium": 2, "low": 1}

SEVERITY_TO_PRIORITY = {
    "critical": "critical",
    "high": "high",
    "medium": "medium",
    "low": "low",
    "none": "low",
}

QUESTION_DISTRIBUTION = {
    "technical": {"easy": 1, "medium": 2, "hard": 1},
    "behavioral": {"easy": 0, "medium": 1, "hard": 0},
    "mixed": {"easy": 1, "medium": 2, "hard": 1},
}


def _compute_interview_readiness_score(
    skill_gap_report: Optional[Dict[str, Any]],
    coding_analytics: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Deterministic interview readiness pre-assessment.
    This scores how PREPARED the student is likely to be, not their actual performance.
    """
    score_components = []

    # 1. Skill coverage factor (from gap report)
    if skill_gap_report:
        coverage = skill_gap_report.get("overall_coverage", 50)
        skill_factor = min(coverage / 100, 1.0) * 30  # Max 30 pts
        score_components.append(("skill_readiness", round(skill_factor, 2), 30))
    else:
        score_components.append(("skill_readiness", 15.0, 30))  # Neutral

    # 2. Coding practice factor
    if coding_analytics:
        summary = coding_analytics.get("summary", {})
        percentile = summary.get("coding_percentile", 50)
        coding_factor = min(percentile / 100, 1.0) * 40  # Max 40 pts
        score_components.append(("coding_practice", round(coding_factor, 2), 40))
    else:
        score_components.append(("coding_practice", 20.0, 40))  # Neutral

    # 3. Problem diversity factor (based on topic coverage)
    if coding_analytics:
        topics = coding_analytics.get("topic_analysis", [])
        strong_topics = sum(1 for t in topics if t.get("strength_level") in ("strong", "competent"))
        diversity_ratio = strong_topics / max(len(topics), 1)
        diversity_factor = diversity_ratio * 30  # Max 30 pts
        score_components.append(("topic_diversity", round(diversity_factor, 2), 30))
    else:
        score_components.append(("topic_diversity", 15.0, 30))

    total = sum(c[1] for c in score_components)
    max_total = sum(c[2] for c in score_components)

    return {
        "readiness_score": round(total, 2),
        "max_score": max_total,
        "percentage": round((total / max_total) * 100, 1) if max_total > 0 else 0,
        "components": [
            {"name": c[0], "score": c[1], "max": c[2]}
            for c in score_components
        ],
    }


def _determine_question_focus(skill_gap_report: Optional[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Determine which skills to focus questions on based on gap analysis.
    Prioritizes gaps by severity.
    """
    focus_areas = []

    if skill_gap_report:
        gaps = skill_gap_report.get("gaps", [])
        for gap in gaps:
            focus_areas.append({
                "skill": gap.get("skill", "General"),
                "current_level": gap.get("current_level", "unknown"),
                "required_level": gap.get("required_level", "intermediate"),
                "severity": gap.get("severity", "medium"),
                "priority": SEVERITY_TO_PRIORITY.get(gap.get("severity", "medium"), "medium"),
            })

        # Also add some strength-testing questions
        strengths = skill_gap_report.get("strengths", [])
        for s in strengths[:2]:  # Top 2 strengths
            focus_areas.append({
                "skill": s.get("skill", "General"),
                "current_level": s.get("level", "intermediate"),
                "required_level": s.get("level", "intermediate"),
                "severity": "none",
                "priority": "low",  # Confirm strengths, don't over-focus
            })

    # Sort by priority weight descending
    focus_areas.sort(
        key=lambda x: PRIORITY_WEIGHTS.get(x["priority"], 1),
        reverse=True,
    )

    return focus_areas


def _sort_roadmap_by_priority(roadmap_items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Deterministic priority sort for roadmap items."""
    return sorted(
        roadmap_items,
        key=lambda x: PRIORITY_WEIGHTS.get(x.get("priority", "low"), 1),
        reverse=True,
    )


def _get_llm():
    """Get LLM for question generation and roadmap creation."""
    return ChatGoogleGenerativeAI(
        model=settings.LLM_MODEL,
        temperature=0.4,  # Slightly more creative for questions
        google_api_key=settings.LLM_API_KEY if settings.LLM_API_KEY else "dummy",
    )


# ---------------------------------------------------------------------------
# Main Agent Node
# ---------------------------------------------------------------------------

def interview_agent_node(state: PlacementState) -> Dict[str, Any]:
    """
    LangGraph Node: Interview Agent.

    1. Reads student_profile, skill_gap_report, coding_analytics from state
    2. Computes interview readiness score (deterministic)
    3. Determines question focus areas from skill gaps (deterministic)
    4. Uses LLM to generate adapted questions + roadmap
    5. ALL LLM output is explicitly labelled as AI-generated
    6. Returns interview_result + roadmap to state
    """
    logger.info("[InterviewAgent] Starting mock interview preparation...")

    student_profile = state.get("student_profile")
    if not student_profile:
        return {
            "errors": ["InterviewAgent: No student profile available."],
            "current_step": "interview_agent",
        }

    skill_gap_report = state.get("skill_gap_report")
    coding_analytics = state.get("coding_analytics")
    matching_result = state.get("matching_result")
    target_roles = state.get("target_roles", ["software_engineer"])

    # ---------- STEP 1: Deterministic readiness pre-assessment ----------
    readiness = _compute_interview_readiness_score(skill_gap_report, coding_analytics)

    # ---------- STEP 2: Determine question focus (deterministic) ----------
    focus_areas = _determine_question_focus(skill_gap_report)

    # ---------- STEP 3: Determine target role for questions ----------
    target_role_title = "Software Engineer"  # Default
    if matching_result:
        matches = matching_result.get("matches", [])
        if matches:
            target_role_title = matches[0].get("role_title", "Software Engineer")

    # ---------- STEP 4: LLM question generation + roadmap ----------
    try:
        llm = _get_llm().with_structured_output(InterviewOutput)

        interview_prompt = f"""
        You are the Interview Agent for a Placement Readiness system.

        CRITICAL RULES:
        1. ALL feedback and evaluations MUST be clearly marked as "[AI-Generated]"
        2. Adapt questions to the student's identified skill gaps
        3. Generate diverse question types (technical, behavioral, coding)
        4. Learning roadmap items must be specific and actionable
        5. Resource recommendations should be real, specific resources
        6. Never make assumptions about the student beyond the data provided

        STUDENT PROFILE:
        - Skills: {[s.get('name') for s in student_profile.get('skills', [])]}
        - Projects: {len(student_profile.get('projects', []))} projects
        - Education: {student_profile.get('education', 'Not specified')}

        TARGET ROLE: {target_role_title}

        SKILL GAP FOCUS AREAS (prioritized by severity):
        {focus_areas[:8]}

        CODING ANALYTICS SUMMARY:
        {coding_analytics.get('summary', {{}}) if coding_analytics else 'Not available'}

        INTERVIEW READINESS SCORE (GROUND TRUTH — context only):
        {readiness}

        Generate:
        1. 5-8 interview questions adapted to this student's gaps
        2. A mock evaluation template (assuming average performance)
        3. 5-10 learning roadmap items prioritized by gap severity
        4. 3-5 specific preparation tips
        """

        result: InterviewOutput = llm.invoke([
            SystemMessage(content=interview_prompt),
            HumanMessage(content="Generate adapted interview questions and learning roadmap.")
        ])

        # Process questions
        questions = []
        for q in result.questions:
            questions.append({
                "text": q.text,
                "type": q.question_type,
                "difficulty": q.difficulty,
                "skill_targeted": q.skill_targeted,
                "expected_answer_outline": q.expected_answer_outline,
                "scoring_rubric": q.scoring_rubric,
                "ai_generated": True,  # ALWAYS mark as AI-generated
            })

        # Process roadmap
        roadmap_items = []
        for item in result.roadmap_items:
            roadmap_items.append({
                "skill": item.skill,
                "title": item.title,
                "description": item.description,
                "priority": item.priority,
                "resources": item.resources,
                "estimated_hours": item.estimated_hours,
                "milestone": item.milestone,
                "ai_generated": True,
            })

        # Sort roadmap by priority
        roadmap_items = _sort_roadmap_by_priority(roadmap_items)

        mock_evaluation = result.mock_evaluation
        if isinstance(mock_evaluation, dict):
            mock_evaluation["ai_generated_disclaimer"] = (
                "[AI-Generated] This evaluation is a template based on the student's profile. "
                "Actual performance evaluation requires a faculty-supervised session."
            )
        else:
            mock_evaluation = {
                "note": "[AI-Generated] Mock evaluation template",
                "ai_generated_disclaimer": "This is a pre-generated template.",
            }

        preparation_tips = result.preparation_tips

    except Exception as e:
        logger.warning(f"[InterviewAgent] LLM generation failed, using fallback: {e}")

        # Deterministic fallback questions
        questions = []
        for i, area in enumerate(focus_areas[:6]):
            questions.append({
                "text": f"Explain your understanding of {area['skill']} and how you've applied it in projects.",
                "type": "technical",
                "difficulty": "medium",
                "skill_targeted": area["skill"],
                "expected_answer_outline": f"Should demonstrate {area['required_level']}-level understanding of {area['skill']}.",
                "scoring_rubric": f"Evaluate depth of {area['skill']} knowledge and practical application.",
                "ai_generated": True,
            })

        # Deterministic fallback roadmap
        roadmap_items = []
        for area in focus_areas:
            roadmap_items.append({
                "skill": area["skill"],
                "title": f"Study {area['skill']} to {area['required_level']} level",
                "description": f"Close the gap: current={area['current_level']}, required={area['required_level']}",
                "priority": area["priority"],
                "resources": [f"Official {area['skill']} documentation", "Practice on LeetCode/HackerRank"],
                "estimated_hours": 20 if area["severity"] in ("critical", "high") else 10,
                "milestone": f"Achieve {area['required_level']} proficiency in {area['skill']}",
                "ai_generated": True,
            })

        roadmap_items = _sort_roadmap_by_priority(roadmap_items)

        mock_evaluation = {
            "overall_score": readiness["percentage"],
            "note": "[AI-Generated] Fallback evaluation based on readiness metrics.",
            "ai_generated_disclaimer": "LLM evaluation unavailable. Using deterministic assessment.",
        }

        preparation_tips = [
            f"Focus on {focus_areas[0]['skill']} — it's your highest priority gap" if focus_areas else "Review fundamentals",
            "Practice coding problems daily on LeetCode or HackerRank",
            "Prepare STAR-format responses for behavioral questions",
        ]

    # ---------- STEP 5: Compute estimated total study hours ----------
    total_study_hours = sum(item.get("estimated_hours", 0) for item in roadmap_items)

    # ---------- STEP 6: Assemble final results ----------
    interview_result = {
        "target_role": target_role_title,
        "readiness_assessment": readiness,
        "questions": questions,
        "total_questions": len(questions),
        "mock_evaluation": mock_evaluation,
        "preparation_tips": preparation_tips,
        "ai_generated_disclaimer": (
            "[AI-Generated] All interview questions, evaluations, and roadmap items in this section "
            "are generated by AI. Faculty sign-off is required for readiness certification."
        ),
        "computed_at": datetime.now(timezone.utc).isoformat(),
    }

    roadmap = {
        "items": roadmap_items,
        "total_items": len(roadmap_items),
        "total_estimated_hours": total_study_hours,
        "focus_summary": f"{len([i for i in roadmap_items if i['priority'] in ('critical', 'high')])} "
                         f"high-priority items, {total_study_hours} total estimated hours",
        "ai_generated_disclaimer": (
            "[AI-Generated] This roadmap is AI-generated based on identified skill gaps. "
            "Consult with your faculty advisor for personalized guidance."
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

    # ---------- STEP 7: Evidence records ----------
    from app.schemas.evidence import EvidenceRecord
    evidence = EvidenceRecord(
        entity_type="interview_preparation",
        evidence_type="ai_generation",
        source="interview_agent",
        content=f"Generated {len(questions)} questions + {len(roadmap_items)} roadmap items "
                   f"for {target_role_title}. Readiness: {readiness['percentage']}%",
        scope_tags=["interview", "roadmap", "ai_generated"],
    ).model_dump()

    audit = AuditEvent(
        action="interview_prepared",
        agent="InterviewAgent",
        timestamp=datetime.now(timezone.utc).isoformat(),
        details={
            "target_role": target_role_title,
            "questions_generated": len(questions),
            "roadmap_items": len(roadmap_items),
            "readiness_score": readiness["percentage"],
            "total_study_hours": total_study_hours,
        }
    )

    logger.info(
        f"[InterviewAgent] Complete — Questions: {len(questions)}, "
        f"Roadmap Items: {len(roadmap_items)}, Readiness: {readiness['percentage']}%"
    )

    return {
        "interview_result": interview_result,
        "roadmap": roadmap,
        "evidence_records": [evidence],
        "audit_events": [audit],
        "current_step": "interview_agent",
    }
