from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict
import operator

from pydantic import BaseModel, Field


class ExecutionStep(BaseModel):
    """A specific step in the execution plan."""
    step_id: str
    agent: str
    description: str
    requires_input_from: List[str] = []


class ExecutionPlan(BaseModel):
    """The master plan generated by the coordinator."""
    goal_summary: str
    steps: List[ExecutionStep]
    estimated_tokens: int = 0
    is_locked: bool = False


class AuditEvent(BaseModel):
    """An event to log to the audit trail."""
    action: str
    agent: str
    timestamp: str
    details: Dict[str, Any] = {}


def append_items(a: List, b: List) -> List:
    """Reducer function to append items to a list in LangGraph state."""
    if not a:
        a = []
    if not b:
        return a
    return a + b


class PlacementState(TypedDict):
    """The full state of a placement readiness workflow run."""
    # Identifiers
    run_id: str
    student_id: str
    
    # User Request Input
    request_context: Optional[str]
    target_roles: List[str]
    
    # Plan
    plan: Optional[ExecutionPlan]
    plan_locked: bool
    
    # Output Models
    resume_data: Optional[Dict[str, Any]]
    student_profile: Optional[Dict[str, Any]]
    skill_gap_report: Optional[Dict[str, Any]]
    coding_analytics: Optional[Dict[str, Any]]
    matching_result: Optional[Dict[str, Any]]
    interview_result: Optional[Dict[str, Any]]
    roadmap: Optional[Dict[str, Any]]
    
    # Internal state
    consent_validated: bool
    evidence_records: Annotated[List[Dict[str, Any]], append_items]
    
    # Validation & Approval
    validation_passed: bool
    failing_checks: List[str]
    approval_status: Literal["pending", "approved", "rejected", "changes_requested"]
    
    # Control
    retry_count: int
    max_retries: int
    current_step: str
    next_node: str
    
    # System
    errors: Annotated[List[str], append_items]
    audit_events: Annotated[List[AuditEvent], append_items]
    budget_remaining: int
